baseurl = "http://fsolt.org"
relativeurls = false
languageCode = "en-us"
title = "Frederick Solt"
theme = "hugo-fs-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
uglyURLS = false
enableEmoji = true
blogdir = "blog"

[permalinks]
    post = "blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "The SWIID"
    url = "/swiid/"
    weight = 2
[[menu.main]]
    name = "Research on Inequality"
    url = "/res/res/"
    weight = 3
[[menu.main]]
    name = "Additional Research"
    url = "/res/add_res/"
    weight = 4
[[menu.main]]
    name = "Teaching"
    url = "/teach/"
    weight = 5
[[menu.main]]
    name = "Published Software"
    url = "/sw/"
    weight = 6
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 7
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 8

[params]
    description = "Income Inequality & Its Consequences, Comparative Political Behavior, and Dynamic Comparative Public Opinion"
    subtitle = "Income Inequality & Its Consequences, Comparative Political Behavior, and Dynamic Comparative Public Opinion"
    home_title = "About"
    home_text = "I am an associate professor in the [Department of Political Science](http://clas.uiowa.edu/polisci/) at the [University of Iowa](http://www.uiowa.edu).  My interests include comparative political behavior and political economy from a cross-national perspective; I am also interested in computational methods for cross-national research.  Much of my work focuses on understanding how---and why---the extent of economic inequality in a country shapes the attitudes and behavior of the people who live there.  I also created and maintain the Standardized World Income Inequality Database (SWIID), which provides the most-comparable data available on income inequality for broadly cross-national research.  Please use the links at left to find out more about the SWIID, my research on the consequences of economic inequality, my work on other topics in comparative politics and political sociology, the courses I teach, my published software, blogged updates and working notes, and my CV."

    author = "Frederick Solt"
    dateFormat = "2006/01/02"
    email = "frederick-solt@uiowa.edu"
    twitter_username = "fredericksolt"
    github_username = "fsolt"
    dataverse_username = "fsolt"
    gscholar_code = "PNwjYEAAAAAJ"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

